### PR TITLE
introduce RuleWithCtx interface (#719)

### LINKED ISSUE #719: Support StopGain with precise trade exit price
I need support for a TakeProfitRule
- which supports a fixed pips/points (like 20 pips)
- that sets the price to the market price and not the close price

Example:
Candle opens at 20 closes at 21 but the wick was at high 21.5
My stop gain / take profit is at 21.3 --> currently the 21 would be the trade price.
But it should be 21.3

### PR DESCRIPTION
**Pull request by golesny**
new interface is used for the base rules and for backward compatibility
added new StopGainRule2 that supports percentage and fixed gain and
price is used as exit price

Fixes #719 .

Changes proposed in this pull request:
- **Enhancement** Added new interface RuleWithCtx to define the trade price
- **Enhancement** AndRule, OrRule, XorRule, NotRule implementing RuleWithCtx
- **Enhancement** new StopGainRule2 that supports percentage and fixed gain and price is used as exit price

### CODE REVIEW

**Comment by nimo23** [comment]
Hi, thanks for your commit. 

But I really think that your commit introduces a lot of influences to stable classes (e.g., bad and vague names, ctx for context (which is also vague), shouldDo (interferes with shouldEnter(), which leads to confusion)  and the other stuff which really adds too much complexitiy, brings too much confusion to stable API. I think, for the one issue you try to solve the whole baggage you provided can be simplified a lot by using only one class..no need to pollute so much classes for such an issue..

**Comment by nimo23** [comment]
Unfortunatly, I don't have time to explain every little step.

At first, you should consider to create only a new Rule or Indicator for your issue... If this is not possible for you, then leave it as you think and use this _special_ solution in **your** fork instead of trying to put this to this repo..this repo is considered for general use cases..your solution introduces too much complexity (pollutes too much stable classes) for a very easy task..

**Comment by nimo23** [comment]
Try to solve your solution by using a Rule or Indicator, don't change all those classes only for your task..if this is not possible, then leave this solution as it is in **your** fork, but I really don't like to see this _special_ solution in this repo..

**Comment by golesny** [comment]
Mmmh, not sure how to solve that in an easy way. TakeProfit/StopLoss braket with 20 pips is not a special case in my eyes.
I'll try to re-work that ... but I guess thats not possible as the BarSeriesManager defines the exit price of the trade and do not ask the strategy nor the rules (separation of concern pattern). I have to check what is possible

**Pull request closed without merging**
