### PR TITLE
Replace Riot chat badge with Discord

### PR DESCRIPTION
**Pull request by milczarekIT**
Fixes #.

Changes proposed in this pull request:
- Replace Riot chat badge with Discord in README.md
- 
- 

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by team172011** [comment]
thanks, but I added he badge already on master. I just had not cherry-picked it because it is not so important on develop branch

**Comment by milczarekIT** [comment]
I saw it on `master`, but it is missing on `develop`, so this is reason why I created this PR.
IMO correct `README.md` is important.

**Comment by team172011** [comment]
okay, so it is the same from master

**Comment by milczarekIT** [comment]
Thanks

**Pull request merged**
