### PR TITLE
Added: Num.isBetween()

### PR DESCRIPTION
**Pull request by nimo23**
- Added method isBetween()
- correct javadoc

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
maven formatter plugin is not executed when using github editor. One more reason to shift the formatting to the CI-server..

**Comment by nimo23** [comment]
>I think the implementation and usage of this kind of method should be up to the user.

the methods I use are only provided by Num, nothing else. And isBetween is a very common math operation..but sure, you decide..

**Comment by nimo23** [comment]
>I think the implementation and usage of this kind of method should be up to the user.

we also have` isGreaterThan`, `isLowerThan`..and similiar..it is the right place to put `isBetween()` within `Num`.

**Comment by team172011** [comment]
similar to `minus()` and `plus()` methods `isGreater|Than` and `isLower|Than` are equivalencies for >|>= and <|<=, operators that can only be applied on primitives in java. isBetween() is a higher level math operation that can easily implemented by the user.

**Comment by nimo23** [comment]
>that can easily implemented by the user.
And why not free up the user from doing it. `isBetween` is a basic aritmethic math operation. And is a common functionality needed for different indicator calculations..

**Comment by nimo23** [comment]
As you know, `isBetween()` can be very well applied on primitives in java..

**Comment by milczarekIT** [comment]
What is more... build is not compiling.
Methods  `isLowerThanOrEqual` and `isLowerThan` do not exist.

**Comment by nimo23** [comment]
We handle range conditions already in Num-Implementation: `isGreaterThan|orEqual`, `isLowerThan|orEqual`. `isBetween` is actually missing and I did a right implementation for all kinds of `Num`-implementations because _it is only based on the methods definined in Num_, nothing else. 

Again, **please explain in facts**, why do you think, there is no need nor it is not the right place to put it into `Num`. The method `isBetween` is a logical consequence of the methods we already defined in `Num`. I cannot share your opinion. It's unlogical to have different kinds of mathematical methods within the Num-implementation and you refuse such a little method which only eats its own bottle. But again: @team172011 you decide.

**Comment by team172011** [comment]
> Again, please explain in facts, why do you think, there is no need nor it is not the right place to put it into Num. 

As I said, we want to provide just basic functionality for the `Num` interface so that it can be handled by users that are familiar with javas primitives like `double` or `int`. E.g `isLessThan` is an necessary method to check if a Num `a` has a lover value than Num `b`, without extracting the delegate and use conditional operators such as `>` for primitives or` a.compareTo(b)` for BigDecimal.
You can compare ta4js `Num` to javas **Double** or **Integer** class or to the **BigDecimal** api. They also do not provide an `isBetween()` method.
As far as `Num` implements the `Comparable` interface we could get rid of `isLowerThan`, `isGreaterThan`, .. , methods as well, but we decided to provided (or to keep) them to simplify the `NaN` handling. 

> The method isBetween is a logical consequence of the methods we already defined in Num.

From my point of view this is not a reason for adding this method. There are millions of "logical consequences" of those methods, should they all be implemented? There is not even a single user request for this simplification, I think because ta4js Num api is simple enough to achieve this range check. Adding more methods means also more effort in maintenance. And speaking of maintenance: you did not provide any unit test for your method. What would be the current result and the expected result of `numOf(5).isBetween(NaN, numOf(10), true, true)?` I think there is a missing `NaN` check...

Especially with those `startInclusive` and `endInclusive` parameters the `isBetween` method does not look like something that makes things easier. The user must read the javadoc to really understand this method and in the end you are just replacing the usage of isLowerThan or isLessThanOrEqual with two boolean parameters.

**Comment by nimo23** [comment]
>The user must read the javadoc to really understand this method 

The `inclusive`-properties are already documented in the API doc..but I can improve the javadoc if there is any unclear description. For the test cases: I find no need, because it only uses methods from `Num` which already provide test cases.

>and in the end you are just replacing the usage of isLowerThan or isLessThanOrEqual with two boolean parameters.

`isBetween()` has different use cases than `isGreaterThan|orEqual`, `isLowerThan|orEqual`.

>There are millions of "logical consequences" of those methods, should they all be implemented?

Look at:

```
>
>=
<
<=
isBetween (actually missing)
```

No more possibilities of range queries can be found, because all possibilities are implemented if we provide `isBetween()`. Having `isBetween()`, the `Num` can be seen as complete.

And `isBetween()` is not only a good alternative of a weaker but controllable `equals()`-method when using `DoubleNum` but it is also a shortcut for indicators needed that method. If I have a few indicators making use of this method, I must duplicate this method: code, maintenance and test cases increases only because we do not abstract this method from the user. For **numercial methods**, range queries are very common and `isBetween()` is a very common range query which deserves the same right as `isGreaterThan|orEqual`, `isLowerThan|orEqual`. Num deserves generalized numerical methods and the best place to put those numerical methods is `Num.class`. I will not debate again, if you are against it then close this issue.

**Pull request closed without merging**
