### PR TITLE
Update Position.java: getProfit()

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- Fixes formula for getProfit() for short position with commission
- 
- 

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
@team172011 can you please verify that my proposed forumula is invalid? I think exit a **short position** and substracting the `getPositionCost()` currently increases the profit, but it should decrease the profit, or?

**Review by team172011 — APPROVED** [review]

**Review by team172011 — CHANGES_REQUESTED** [review]
fix is not valid

**Comment by team172011** [comment]
> @team172011 can you please verify that my proposed formula is invalid? I think exit a **short position** and substracting the `getPositionCost()` currently increases the profit, but it should decrease the profit, or?

ah yes, I think this fix is not correct. `getGrossProfit(exit.getPricePerAsset())` is already returning the _profit_ and you have to subtract the `getPositionCost` in both ways

**Comment by nimo23** [comment]
ok, fine:)

**Pull request closed without merging**
