### PR TITLE
Fix/linear transaction costw xls

### LINKED ISSUE #134: LinearTransactionCostCriterion
error in calculation

### PR DESCRIPTION
**Pull request by edlins**
Fixes #134 .

Changes proposed in this pull request:
- Fix LTCC calculation
- Add xls file and unit tests
- 

- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by edlins** [comment]
I created a new branch off enhance/xls-testing.  Once that's merged, then this should merge with 3 commits / 6 files changed like
https://github.com/edlins/ta4j/compare/enhance/xls-testing...edlins:fix/LinearTransactionCostwXLS
Let me know if I should submit this differently.

**Comment by edlins** [comment]
So, I do like the idea of using XLS for validation for both indicators and criteria.  However, I feel uncomfortable having the asserts comparisons in XlsTestsUtils instead of in the indicator/criterion test classes.  Would it be better to have FancyIndicatorTest with tests like
```
Indicator<Decimal> expected = genXlsIndicator(class, file, column, params);
Indicator<Decimal> actual = new FancyIndicator(
    new ClosePriceIndicator(getXlsSeries(class, file)), params);
TATestsUtils.assertValuesEquals(actual, expected);
```
instead of
```
testXlsIndicator(class, file, column, (inputSeries) -> {
    return new FancyIndicator(new ClosePriceIndicator(inputSeries), params), params);
    });
```
I'm sure I've missed something but the first version looks so much cleaner.  In the second version, it's not even clear what's being compared.  Clarity is essential.

Regardless, how would you like to handle these branches?  It's getting a little twisty with develop->feature1->feature2->feature3...

**Comment by team172011** [comment]
I have merged your xls enhancement first and now i try to merge this branch into develop. The `LinearTransactionCostCriterionTest` throws NPE. And StackTrace ends in function `XlsTestsUtils#readDataAfterHeader` in this line:

```java
if (noHeader && evaluator.evaluate(row.getCell(0)).formatAsString().contains("Date")) {
    noHeader = false;
}
```
Maybe because of `getCell(0) `?

By the way I have simplified the transformation in testXlsCriterion to
```java
Decimal[] decimalParams = Arrays.stream(params).map(p -> Decimal.valueOf(p.toString())).toArray(Decimal[]::new);
```
So we need no typecast and additional map operation.

**Comment by team172011** [comment]
NPE is thrown because you have not filled the first Cell of Row 8... I will add additional check if row is not available

**Comment by team172011** [comment]
I see you have done exactly the same in this PR^^

**Comment by edlins** [comment]
```
Decimal[] decimalParams = Arrays.stream(params).map(p -> Decimal.valueOf(p.toString())).toArray(Decimal[]::new);
```
Changes like this are exactly why I broke this out to multi-line.  Multi-line is much more clear when there are diffs..

**Pull request merged**
