### PR TITLE
Add svn to gitignore

### PR DESCRIPTION
**Pull request by diffstorm**
Fixes #.

Changes proposed in this pull request:
- Added .svn directory to gitignore

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by diffstorm** [comment]
> Hi, please update your feature branch

Hi, what do you mean? Please redirect me about your request.

**Comment by nimo23** [comment]
@diffstorm https://github.com/ta4j/ta4j/pull/551#issuecomment-602241588

**Comment by nimo23** [comment]
@diffstorm You actually commit 100 files only to change one file and `.gitignore`. This is because you use stale versions of develop branch. Update your local develop branch and make a new PR with only one commit. This makes it easy for others what to track the changes..

**Comment by diffstorm** [comment]
I just reverted my other files. Hope it is ready

**Pull request closed without merging**
