### PR TITLE
rename to DecimalNum

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- rename `PrecisionNum` to `DecimalNum`
- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
According to https://github.com/ta4j/ta4j/issues/476.

@team172011 Please resolve conflict files.

**Comment by nimo23** [comment]
@team172011 please resolve conflicting files..

**Comment by nimo23** [comment]
@team172011 **This PR is waiting over 4 month!**

I will not debate over and over again only to convince @milczarekIT that **a precicion is NOT a number**!

**Decimal or Double is a number**, hence we have DoubleNum and DecimalNum (because Precicion is NOT a number!). Did you finally understand? In future, I will refuse to debate on such obvious things with people having no arguments but refusing again and again! Such an attitude is very unproductive.

**Comment by decebals** [comment]
@nimo23 
> @team172011 Please resolve conflicting files.

I think you can do it yourself. Just merge the `develop` branch (if I understood correctly) in the feat/PR branch, resolve the conflicts and commit/push again the code. It's a hint to increase the chance that @team172011 to merge (with squash) this PR :smile:.

> I will not debate over and over again only to convince @milczarekIT that a precicion is NOT a number!

Both of you are a great gain for this project (they are not to many committers for this project). I think it would be nice to learn to work together :smile:. 

Sorry, that I have intervened in this PR, without to put a concrete value on the table.

**Comment by nimo23** [comment]
Thanks for the hint, but I get the message:

> This branch has conflicts that must be resolved
> Only those with write access to this repository can merge pull requests.

I dont have write access, so I cannot resolve the conflicts..

**Comment by nimo23** [comment]
>I think it would be nice to learn to work together 

Yes, I think also, sorry for my rude tone.

**Comment by decebals** [comment]
@nimo23 
> I dont have write access, so I cannot resolve the conflicts..

Maybe I am missing something, but I think that is possible to __resolve__ the conflicts (not to merge the PR). Please take a look on [these] steps (I'm too lazy in this moment to write myself these steps :smile: ). You can try.

**Comment by nimo23** [comment]
I cannot resolve the conflicts because I am not allowed to resolve the conflicts:

Screenshot at Mar 17 22-56-23

**Comment by decebals** [comment]
> I cannot resolve the conflicts because I am not allowed to resolve the conflicts:

Yes. You cannot resolve the conflicts from GitHub UI.
I understood from what I read that the "Resolve conflicts" button is disabled because it's too complex to resolve the conflicts via GitHub UI.

**Comment by nimo23** [comment]
Anyway, better to let @team172011 do it..I cannot resolve the conflicts.

**Comment by milczarekIT** [comment]
@nimo23, @decebals  send you instruction on how to do it
See commands:
```
git checkout <feature-branch-name>
git pull upstream development
```
And then commit and push changes to this remote branch.


I confirm what @decebals wrote:
1) Conflicts can be resolved by you.
2) Only @team172011 can merge pull requests, but merge conflicts must be resolved before (e.g. by PR's author).

**Comment by team172011** [comment]
@nimo23 I will make a new PR if you are not able to resolve conflicts

**Comment by nimo23** [comment]
@team172011 thanks, yes please make a new PR.

**Pull request closed without merging**
