### PR TITLE
Configured properly formatter validation in Travis build

### PR DESCRIPTION
**Pull request by milczarekIT**
Fixes #.

Changes proposed in this pull request:
- Enabled features implemented in https://github.com/ta4j/ta4j/pull/438, disabled by https://github.com/ta4j/ta4j/pull/544
- 
- 

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md` - no need

### CODE REVIEW

**Comment by milczarekIT** [comment]
Build is failing, because project is not formatted correctly.
Before this PR, https://github.com/ta4j/ta4j/pull/592 should be merged

**Comment by milczarekIT** [comment]
Some time ago (https://github.com/ta4j/ta4j/pull/508) I fixed this issue. Once again feature provided in  #438 has been disabled.

@team172011  you agreed to this change (#438, #320). Please do not remove code formatting.

**Comment by milczarekIT** [comment]
https://github.com/ta4j/ta4j/pull/592 has been merged.
Build on this PR retriggered and now develop is passing with enabled formatting validation.

**Comment by milczarekIT** [comment]
Up

**Comment by milczarekIT** [comment]
Up. This PR is waiting over 2 months

**Comment by nimo23** [comment]
Yes, other PRs are waiting, too. Actually, I will also **not** push any other PRs as long as this project stucks. The progress of this project will really not benefit when PRs are waiting over 6 month and no feedback of the project maintainer is given so far. Others will not contribute if this this project is stale for too long..

**Pull request merged**
