### PR TITLE
Bugfix/time series max bar count (in progress..)

### LINKED ISSUE #324: BaseTimeSeries problem with getSubList
Hey guys,

I have a BaseTimeSeries where I set the MaximumBarCount for (in my example to ). Every minute there is a new Bar added, When I call the getSubList method after a Bar was added with the follwing statement:

`timeSeries.getSubSeries(timeSeries.getEndIndex() - (timespan + 1), timeSeries.getEndIndex())`

an Exception is thrown:

`java.lang.IndexOutOfBoundsException: toIndex = 40321
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1012)
	at java.util.ArrayList.subList(ArrayList.java:1004)
	at org.ta4j.core.BaseTimeSeries.cut(BaseTimeSeries.java:423)
	at org.ta4j.core.BaseTimeSeries.getSubSeries(BaseTimeSeries.java:199)
	at de.coin.research.service.impl.Ta4JTimeSeriesServiceImpl.getTimeSeries(Ta4JTimeSeriesServiceImpl.java:84)
	at de.coin.research.service.impl.Ta4JTimeSeriesServiceImpl$$FastClassBySpringCGLIB$$70f1fbc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at de.coin.research.aop.logging.LoggingAspect.logAround(LoggingAspect.java:85)
	at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at de.coin.research.service.impl.Ta4JTimeSeriesServiceImpl$$EnhancerBySpringCGLIB$$c7a0d204.getTimeSeries(<generated>)
	at de.coin.research.service.mapper.Ta4JMapper.getTimeSeries(Ta4JMapper.java:239)
	at de.coin.research.service.mapper.Ta4JMapper.mapToIndicator(Ta4JMapper.java:85)
	at de.coin.research.service.mapper.Ta4JMapper.mapToIndicator(Ta4JMapper.java:81)
	at de.coin.research.service.mapper.Ta4JMapper.getIndicatorFromConfig(Ta4JMapper.java:546)
	at de.coin.research.service.mapper.Ta4JMapper.mapToRule(Ta4JMapper.java:261)
	at de.coin.research.service.mapper.Ta4JMapper.mapToRule(Ta4JMapper.java:246)
	at de.coin.research.service.mapper.Ta4JMapper.mapToStrategy(Ta4JMapper.java:517)
	at de.coin.research.service.mapper.Ta4JMapper$$FastClassBySpringCGLIB$$af6a4255.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at de.coin.research.service.mapper.Ta4JMapper$$EnhancerBySpringCGLIB$$a72f5c54.mapToStrategy(<generated>)
	at de.coin.research.business.StrategyRunner.runStrategies(StrategyRunner.java:59)
	at de.coin.research.business.StrategyRunner$$FastClassBySpringCGLIB$$bebd3d4e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at de.coin.research.business.StrategyRunner$$EnhancerBySpringCGLIB$$ee1c70df.runStrategies(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

The problem is, that when the BaseTimeSeries exceed the MaximumBarCount it removes the oldest Bar (which is correct) but raises the endIndex by 1 (which is wrong I think). This leads to the index out of Bounds error when you call the getSubList mehtod via endIndex.

### PR DESCRIPTION
**Pull request by team172011**
This enables to get the correct `endIndex` if `maxBarCount` has been
exceeded.

I think it is also desirable to have the first index of a `TimeSeries`
always be zero. To reach this the `BaseTimeSeries#setMaximumBarCount`
function must be modified or deleted.

Fixes #324.

Changes proposed in this pull request:
- adding seriesEndIndex-- to removeExceedingBars() method in BaseTimeSeries

- [ ] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by jansoren** [comment]
@team172011 - Merging this with `master` and not with `develop`, is that intentional?

**Comment by team172011** [comment]
@jansoren I think I will need some time to implement this altogether. Subsequently I could make a hotfix to master branch, but than it will still not be available on maven

**Comment by jansoren** [comment]
@team172011 I'm not thinking of the fix. It seems that this PR should be merged with `develop` and not directly to `master`

**Comment by team172011** [comment]
ah, thanks for the hint

**Comment by team172011** [comment]
outdated and not compatible with new features. Must be fixed by new PR

**Comment by nimo23** [comment]
>I think it is also desirable to have the first index of a TimeSeries
always be zero. To reach this the BaseTimeSeries#setMaximumBarCount
function must be modified or deleted.

@team172011 Can you explain why you wanted to remove `BaseTimeSeries#setMaximumBarCount`. And one question: How would a non empty barSeries behave if we call `setMaximumBarCount()` afterwards? Can I change it maximumBarCount afterwards or are there any side effects? Would be nice to include such hints within the javadoc.

**Pull request closed without merging**
