### PR TITLE
Implemented backtesting example - SimpleMovingAverageBacktesting

### PR DESCRIPTION
**Pull request by jansoren**
Changes proposed in this pull request:
- Created a backtesting example to give better understanding of how backtesting is working in Ta4j

A few backtesting questions:
1. In the `seriesManager.run`-method it is possible to set `amount`. How can I see the affect on the result?
2. Is there an easyer way to set a PrecisionNum the `PrecisionNum.valueOf(50)`?
3. In the TradingRecord, what is the difference between buyOrders/sellOrders and entryOrders/ExitOrders?

### CODE REVIEW

**Comment by jansoren** [comment]
4. Can anyone explain the different Criterions and what the different calculations mean?

**Comment by edlins** [comment]
Please add a test driver for any new example apps, like [this](https://github.com/ta4j/ta4j/blob/develop/ta4j-examples/src/test/java/ta4jexamples/QuickstartTest.java).

**Comment by jansoren** [comment]
@edlins - I have now added tests for the new code 👍

**Comment by edlins** [comment]
Thanks.  Output looks okay in the travis log but I didn't validate the values.

**Comment by jansoren** [comment]
@edlins - The values are validated through this test -> `ProfitLossCriterionTest`

**Comment by jansoren** [comment]
@edlins - Could you please tell me what I have to do to get this PR approved?

**Comment by edlins** [comment]
@team172011 runs the show here.

**Comment by jansoren** [comment]
@team172011 - could you please review the PR ?

**Comment by team172011** [comment]
looks good. Thanks!

**Comment by graph1zzlle** [comment]
This doesn't not work for short trade right ?

**Pull request merged**
