### PR TITLE
Pnl package

### PR DESCRIPTION
**Pull request by nimo23**
Added Pnl-package within criteria-package with following contents:
- GrossReturnCriterion (moved from criteria to pnl)
- NetProfitCriterion (renamed and moved from criteria to pnl)
- NetLossCriterion (added to pnl)
- GrossProfitCriterion (renamed and moved from criteria to pnl)
- GrossLossCriterion (added to pnl)

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
@team172011 please resolve the conflicts. I have no write access.

**Comment by nimo23** [comment]
@team172011 Please merge this PR before other PR's, so I don't have to "resolve conflicts" afterwards because of the change from other PR's.

**Comment by team172011** [comment]
what means pnl?

**Comment by nimo23** [comment]
PnL stands for Profit and Loss:

- https://en.wikipedia.org/wiki/PnL_Explained
- https://www.wallstreetoasis.com/finance-dictionary/what-is-profit-and-loss-pnl

**Pull request closed without merging**
