### PR TITLE
Indicator window rules

### PR DESCRIPTION
**Pull request by edlins**
Fixes #.

Changes proposed in this pull request:
- Add *IndicatorWindowRules

- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by edlins** [comment]
Just another one of my personal items, transparent addition.

**Comment by team172011** [comment]
I think this Rule will be mostly redundant with `InSlope ` and `InPipe ` rule

**Comment by edlins** [comment]
Hmm, I don't see how those rules allow you to say "satisfied if 75% of the previous 20 indicator values (any 15 out of the 20) are greater than 65", but I'll just keep these weird rules to myself.  I may submit a few more PRs as I'm syncing to 0.11 but don't feel obligated to take them unless you want.  Just figured I'd offer them as I work through the diffs.

**Comment by team172011** [comment]
You could consider to modify the existing rules if you think this is a necessary feature

**Pull request closed without merging**
