### PR TITLE
fixed expectancy criterion calculation, updated unit tests, noted in …

### LINKED ISSUE #926: [BUG] ExpectancyCriterion Incorrect Calculation
**I have checked existing issues and wiki**
- [X] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [X] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Describe the bug**
The Expectancy calculation is incorrect. In it's current form, it can only ever be negative or zero.

**To Reproduce**
1. Run ExpectancyCriterionTest.calculateOnlyWithProfitPositions(). The trading record has 100% win rate with positive overall profit yet the expectancy score is 0.

**Expected behavior**
In the above unit test the expectancy should be 1.0

**Additional context**
The expectancy formula linked in the comments (https://www.straightforex.com/advanced-forex-course/money-management/two-important-things-to-be-considered/) is incorrect, which is likely the root cause of this bug.

### PR DESCRIPTION
**Pull request by TheCookieLab**
Fixes #926

Changes proposed in this pull request:
- Fixed ExpectancyCriterion calculation
- Updated unit tests
- updated changelog

- [X] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by team172011** [comment]
@TheCookieLab I agree that the calculation of the expectancy looks wrong. But I am not sure if your fix produces the correct results when looking into the fixed unit tests.

For example the first unit tests that was only looking at winning trades had a result value of 0. I do not know what this should mean. With your fix it results in 1, but I do not know how to interpret this value?

```java
@Test
public void calculateOnlyWithProfitPositions() {
    MockBarSeries series = new MockBarSeries(numFunction, 100, 110, 120, 130, 150, 160);
    TradingRecord tradingRecord = new BaseTradingRecord(Trade.buyAt(0, series), Trade.sellAt(2, series),
             Trade.buyAt(3, series), Trade.sellAt(5, series));

     AnalysisCriterion avgLoss = getCriterion();
     assertNumEquals(0, avgLoss.calculate(series, tradingRecord)); // 0 is wrong,  but I think 1 as well
 }
```

In my understanding the formula of the expectancy should look like: 

`e = (% of winning positions X % of avg. profit per position) – (% of losing positions X % of avg. loss per position)`

In the mentioned unit tests we have two trades. Both are winning trades so the **% of winning positions** is 100% and the **% of losing positions** is 0%. The first trades has a profit of 20% (120/100-1) and the second trade has a profit of 23% (160/130-1). That means the **% of avg. profit per position** is 21.54% ((20% + 23%) / 2) and the **% of avg. loss per position** is 0%. This results in:

`(100% * 21.54) - (0% * 0%) = 21.54%`

I would interpret this as the expectancy is positiv with a win of 21.54% per trade.

**Review by team172011 — CHANGES_REQUESTED** [review]
See comments

**Comment by TheCookieLab** [comment]
@team172011 If I'm not mistaken, the AW and AL terms are not percentages but rather raw values. In the [link](https://www.straightforex.com/advanced-forex-course/money-management/two-important-things-to-be-considered/) provided in the comments they define:

> AW = Average winning trade in terms of $
> AL = Average losing trade in terms of $ 

The current implementation produces an expectancy of 0.446 when using the params found in the link so that matches up.

Here is a second example of calculating expectancy which also uses "raw" values rather than percentages: https://evilspeculator.com/key-concepts-in-risk-management/

An exercise using the values in the 2nd example also produces the matching result of 0.8

```
@Test
    public void calculateWith30PercentWinRateFor5REachAnd70PercentLoseRateFor1REach() {
        MockBarSeries series = new MockBarSeries(numFunction, 1, 6, 1, 6, 1, 6, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1);
        TradingRecord tradingRecord = new BaseTradingRecord(Trade.buyAt(0, series), Trade.sellAt(1, series),
                Trade.buyAt(2, series), Trade.sellAt(3, series),
                Trade.buyAt(4, series), Trade.sellAt(5, series),
                Trade.buyAt(6, series), Trade.sellAt(7, series),
                Trade.buyAt(8, series), Trade.sellAt(9, series),
                Trade.buyAt(10, series), Trade.sellAt(11, series),
                Trade.buyAt(12, series), Trade.sellAt(13, series),
                Trade.buyAt(14, series), Trade.sellAt(15, series),
                Trade.buyAt(16, series), Trade.sellAt(17, series),
                Trade.buyAt(18, series), Trade.sellAt(19, series));

        AnalysisCriterion expectancy = getCriterion();
        assertNumEquals(0.8, expectancy.calculate(series, tradingRecord));
    }
```

**Review by team172011 — APPROVED** [review]

**Comment by TheCookieLab** [comment]
@team172011 I certainly could be mistaken but my impression is that expectancy should be thought of as the probability of a win weighted by expected payout. It's useful for decision making in the face of uncertainty (i.e. how much to wager on a bet) but not really designed for scenarios that are guaranteed (i.e. 100% success rate).

**Pull request merged**
