### PR TITLE
Feature/recursive sma indicator

### PR DESCRIPTION
**Pull request by brintal**
Changes proposed in this pull request:
- **RecursiveSMAIndicator**: New indicator for faster SMA calculation
The current SMA implementation is very slow when calculated for large timeframes (>10,000 bars). This change introduces a new, recursive implementation for the SMA using this algorithm:
image
Source: https://de.wikipedia.org/wiki/Gleitender_Mittelwert#Online-Berechnung (only available in the german wikipedia)
Tests for proving equality to the SMAIndicator and comparing performance are provided.

- [X] added an entry to the unreleased section of `CHANGELOG.md`

### CODE REVIEW

**Comment by brintal** [comment]
The changes in Files other than RecursiveSMAIndicator.java, RecursiveSMAIndicatorTest.java and CHANGELOG.md were done by the formatter-maven-plugin which were necessary to pass the "Validate source code / build (pull_request)" check.

**Comment by team172011** [comment]
@brintal thanks for your PR. This will be included in next release

**Comment by brintal** [comment]
@team172011 
I had some weird behavior that I couldn't explain yet when using this indicator. I will look into it more and reopen the pull request once I figure everthing out.

**Comment by nimo23** [comment]
>I had some weird behavior that I couldn't explain yet when using this indicator.

@brintal are you working on this? Maybe you can create a new PR (as a Draft PR), so we can try to solve these weird behaviour togehter?

**Pull request closed without merging**
