### PR TITLE
Implement the Zig Zag indicator

### LINKED ISSUE #363: Zig Zag Indicator
Anyone got a [Zig Zag indicator](https://www.investopedia.com/terms/z/zig_zag_indicator.asp) implementation/calculation?

### LINKED ISSUE #858: Implement the Zig Zag indicator
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**
The [Zig Zag indicator](https://www.investopedia.com/terms/z/zig_zag_indicator.asp) is missing from Ta4j project.

**Describe the solution you'd like**
Implement the Zig Zag indicator.

### PR DESCRIPTION
**Pull request by ecovaci**
Fixes #858.

Changes proposed in this pull request:
- Implement the Zig Zag indicator
- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by ecovaci** [comment]
Bump

**Comment by Cypher01** [comment]
Why was this pull request deleted?

**Comment by francescopeloi** [comment]
@Cypher01 I have the same question :D did you find an answer?

**Comment by francescopeloi** [comment]
maybe because of this comment: https://github.com/ta4j/ta4j/issues/858#issuecomment-1507561832

**Comment by Cypher01** [comment]
That makes sense. So a more stable implementation would be required. The first thing that comes to my mind is to use a simple CachedIndicator as a helper to store the last extreme. But that's just an initial ideal, don't know if this would work.

Who has time to implement the ZigZagIndicator again? Volunteers, step forward! :smiley:

**Comment by francescopeloi** [comment]
I'll look into it but cannot promise anything :smile: it'd be my first indicator so I need to learn well the framework/basics

**Pull request closed without merging**
