### PR TITLE
Remove unused in Quickstart

### PR DESCRIPTION
**Pull request by izeye**
This PR removes an unused statement in `Quickstart`.

### CODE REVIEW

**Comment by edlins** [comment]
Hello, and thank you for your interest!  Please read
https://ta4j.github.io/ta4j-wiki/How-to-contribute
PRs against `master` branch are not accepted.  Please PR against `develop`.

**Comment by izeye** [comment]
@edlins Thanks for the feedback! I should have read it first. I'll try to change the target branch to the `develop` if possible here or create another one.

**Comment by izeye** [comment]
@edlins Re-targeted to the `develop` branch now.

**Comment by edlins** [comment]
Much better, thanks!
I've reviewed this and it's fine to merge.  However, what might be even better is to actually use the `CashFlow` and print a message with `getValue()` on the end index.  But that's optional.

**Comment by team172011** [comment]
@edlins I also thought to use it instead of deleting it, but it would require more than just a getValue call (it must print several cash flow values to make sense and this is to much for a quickstart).

**Pull request merged**
