### PR TITLE
Closes #1087

### LINKED ISSUE #1087: [BUG] ParabolicSarIndicator throws NPE from getValue() method
Hello!
In continuation of #973:
Unfortunately current solution #975 doesn't work as expected. It can be checked by test like this:
```java
    @Test
    public void growingBarSeriesTest() {
        ZonedDateTime now = ZonedDateTime.now();
        List<Bar> bars = new ArrayList<>();
        bars.add(new MockBar(now, 74.5, 75.1, 75.11, 74.06, 0, 0, 0, numFunction));

        MockBarSeries mockBarSeries = new MockBarSeries(bars);
        mockBarSeries.setMaximumBarCount(3);

        mockBarSeries.addBar(new MockBar(now.plusSeconds(1),75.09, 75.9, 76.030000, 74.640000, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(2),79.99, 75.24, 76.269900, 75.060000, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(3),75.30, 75.17, 75.280000, 74.500000, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(4),75.16, 74.6, 75.310000, 74.540000, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(5),74.58, 74.1, 75.467000, 74.010000, 0, 0, 0, numFunction));

        ParabolicSarIndicator sar = new ParabolicSarIndicator(mockBarSeries);

        assertEquals(NaN.NaN, sar.getValue(mockBarSeries.getBeginIndex()));
        assertEquals(NaN.NaN, sar.getValue(mockBarSeries.getRemovedBarsCount()));

        assertNotEquals(NaN.NaN, sar.getValue(mockBarSeries.getRemovedBarsCount() + 1));
        assertNotEquals(NaN.NaN, sar.getValue(mockBarSeries.getEndIndex()));
    }
```

This will throws NPE:
```java
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null

	at org.ta4j.core.indicators.ParabolicSarIndicator.calculateInternal(ParabolicSarIndicator.java:153)
	at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:116)
	at org.ta4j.core.indicators.ParabolicSarIndicator.calculate(ParabolicSarIndicator.java:47)
	at org.ta4j.core.indicators.CachedIndicator.getValue(CachedIndicator.java:126)
	at org.ta4j.core.indicators.RecursiveCachedIndicator.getValue(RecursiveCachedIndicator.java:89)
	at org.ta4j.core.indicators.ParabolicSarIndicatorTest.growingBarSeriesTest(ParabolicSarIndicatorTest.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

I guess we should reconsider the algorithm of [CachedIndicator](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/CachedIndicator.java) before trying to fix [ParabolicSarIndicator](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/ParabolicSarIndicator.java).

### PR DESCRIPTION
**Pull request by zscauer**
Fixes ta4j/ta4j#1087.

Changes proposed in this pull request:
- Change [CachedIndicator](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/CachedIndicator.java) to simplify logic by using `Map` instead of `List`.
- Change [ParabolicSarIndicator](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/ParabolicSarIndicator.java) to not evaluate values from 0 index, and use removedBarsCount instead, because series with removed bars doesn't have values at indexes less then removed bars counter. When indicator get values from non-existent index, it actually receive value at removedBarsCount index instead, but using it like real values and produce fake values (for itself too) because of it.
- Change [ParabolicSarIndicatorTest](https://github.com/ta4j/ta4j/blob/master/ta4j-core/src/main/java/org/ta4j/core/indicators/ParabolicSarIndicatorTest.java) to test not only series without removed bars.

### CODE REVIEW

**Comment by team172011** [comment]
@zscauer thanks for reporting this but, but I do not think that this PR is fixing the problem. 

1. Your changes in the `CachedIndicators` are questionable. Just replacing the list with a map and ignoring the size and index management seems not to be an appropriate improvement nor a simplification. Please look at #907 and linked topics to get an idea of the current caching logic and possible improvements.

2. I don not understand your fix of the `ParabolicSarIndicator`. I think using the `removedBarCounts` as a `startIndex` or replacing the current `index` with `removedBarCounts` does not make sense in any case.

But I think there is a bug like you described in #1087 please have a look at my comment there

**Comment by zscauer** [comment]
Hello @team172011!
Answering to you 2nd question:
If you try to debug some simple test like that, for example:
```java
    @Test
    public void usingCorrectSeriesIndexTest() {
        // Index of each bar will be stored in close price, after the point (price 1.0 = [0], price 1.5 = [5])
        // to define initial index after bar removes.
        ZonedDateTime now = ZonedDateTime.now();
        List<Bar> bars = new ArrayList<>();
        bars.add(new MockBar(now, 1.0, 1.0, 1.0, 1.0, 0, 0, 0, numFunction));

        MockBarSeries mockBarSeries = new MockBarSeries(bars);
        mockBarSeries.setMaximumBarCount(3);

        mockBarSeries.addBar(new MockBar(now.plusSeconds(1),1.0, 1.1, 1.1, 1.0, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(2),1.1, 1.2, 1.2, 1.1, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(3),1.2, 1.3, 1.3, 1.2, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(4),1.3, 1.4, 1.4, 1.3, 0, 0, 0, numFunction));
        mockBarSeries.addBar(new MockBar(now.plusSeconds(5),1.4, 1.5, 1.5, 1.4, 0, 0, 0, numFunction));

        Num firstBarPrice = mockBarSeries.getBar(0).getClosePrice(); // == 1.3
        assertNumEquals(firstBarPrice,  mockBarSeries.getBar(mockBarSeries.getRemovedBarsCount()).getClosePrice());

        ParabolicSarIndicator sar = new ParabolicSarIndicator(mockBarSeries);

        assertEquals(NaN.NaN, sar.getValue(3));
    }
```
You will see, that `protected Num calculate(int index)` method of `ParabolicSarIndicator` class is calling `private Num calculateInternal(int index)` from 0 to current index all the time, but [0] index (also as [1] and [2]) returns [3] bar, but indicator calculating (based on `getBarSeries().getBar(index).getClosePrice()`) and caching values for them like there are different bars, but they are actually not, and `getBarSeries().getBar(index).getClosePrice()` always returning close price of [3] bar.

**Comment by team172011** [comment]
@zscauer thanks, I understand. I was (like in other issues) confused of our maximum bar count feature, that is returning always the same bar for indices < (endIndex - maxBarCount). That means in your example, when you add more than 3 bars, the value from `getEndIndex` is growing, but the `getBeginIndex` method is still returning 0. 

So the bars of the bar series of your example look like this:

```
Bar for getBar( 0 ) closePrice 1.3 endtime 17:39:43.192181 (equals getBar( 3 ))
Bar for getBar( 1 ) closePrice 1.3 endtime 17:39:43.192181 (equals getBar( 3 ))
Bar for getBar( 2 ) closePrice 1.3 endtime 17:39:43.192181 (equals getBar( 3 ))
Bar for getBar( 3 ) closePrice 1.3 endtime 17:39:43.192181
Bar for getBar( 4 ) closePrice 1.4 endtime 17:39:44.192181
Bar for getBar( 5 ) closePrice 1.5 endtime 17:39:45.192181
(removedBarCount = 3)
```

But the indicator should only work with index 5, 4 and 3 if the bar series has a maxBarCount of 3 (bars of index 2, 1 and 0 are euqaul to bar at index 3 or rather equal to the first bar of the maxBarCount window).

Your fix ensures exactly this behaviour -> do not calculate for `indices < removedBarCount`.

Like already mentioned, when debugging your example of #1088 I found out that the root cause for the NPE is a call in the calculateInternal method:

```java
        Num priorSar = getValue(index - 1);
```
This method call works fine as far as the value for `index -1` is already cached. But if the value is not cached, the `calcuate` method is executed again and cleans the maps and recalculates the values.

So far I could not reproduce this bug with your fix and I think it is correct behaviour (with your fix) to calculate previous uncached values, because the calculation will refill the maps like `isUpTrendMap` correctly up to `index -1`.

**Comment by team172011** [comment]
Fix with correct usage of BarSeries#getBeginIndex #1087

**Comment by zscauer** [comment]
Dear @team172011!
Can you please tell me, why exactly you don't want to keep changes under my authorship and think that would be better to merge my contribution into your changes?

**Comment by team172011** [comment]
@zscauer my PR is only another suggestion that can be discussed. We can also use and enhance this initial PR from you with my suggested changes regarding the beginIndex of the BaseBarSeries.

Furthermore we should not touch the CachedIndicator.

**Comment by zscauer** [comment]
@team172011, @nimo23 ok, thank you. I reverted changes in CachedIndicator.

**Review by team172011 — APPROVED** [review]

**Comment by zscauer** [comment]
@team172011 Hello!
Can you please help with step of validation?
I don't understand how I should format code to pass through.
When I run this step from IDEA it finishes success with no errors.

**Comment by zscauer** [comment]
@nimo23 thank you!

**Pull request merged**
