### PR TITLE
Fixed TotalLossCriterion calculations for short trades.

### PR DESCRIPTION
**Pull request by kennethjor**
Changes proposed in this pull request:
- Fixed TotalLossCriterion calculations for short trades.

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by milczarekIT** [comment]
Travis build fails due to:

> [ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.10.0:validate (default-cli) on project ta4j-core: File '/home/travis/build/ta4j/ta4j/ta4j-core/src/main/java/org/ta4j/core/analysis/criteria/TotalLossCriterion.java' has not been previously formatted.  Please format file and commit before running validation! -> [Help 1]

**Comment by kennethjor** [comment]
@milczarekIT Applied.

**Comment by team172011** [comment]
Thanks @kennethjor. can you please resolve conflict. I will merge when travis ci is online again

**Comment by kennethjor** [comment]
Conflicts fixed. Also ran the formatter, hence the extra files.

**Pull request merged**
