### PR TITLE
Update BarSeriesUtils.class

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- Added javadoc

### CODE REVIEW

**Comment by nimo23** [comment]
Due to https://github.com/ta4j/ta4j/pull/508/commits/2c878381ea5a090f1483e1a2539926cbcf799be8 

> The command "mvn -B test license:check formatter:validate" exited with 1.

Why not add `formatter:format` ? 
`mvn -B test license:check formatter:format formatter:validate`

Actually, user cannot do the task manually when they create a PR within github editor.

**Comment by milczarekIT** [comment]
Because `formatter:format` only formats code and it is not committed and pushed to repo.
If `formatter:format` will be added, then it is required to add additional step to travis (to push changes to repo). Code should be formatted by user, it can be done automatically by maven plugin, build only checks if code is formatted correctly.

**Comment by nimo23** [comment]
@team172011 maybe you can improve the build step as suggested in https://github.com/ta4j/ta4j/pull/456#issuecomment-531818365. I will see other contributers having issues with that so better to shift the formatting to the server..

**Comment by nimo23** [comment]
The code formatting issues which will lead to contributing issues for others has already discussed in https://github.com/ta4j/ta4j/issues/320 and I see that there is no progess in that. Btw, I someone uses GitHub-Editor then the code formatting issue always happens. Not nice!

**Comment by nimo23** [comment]
replaced by https://github.com/ta4j/ta4j/pull/553

**Pull request closed without merging**
