### PR TITLE
Add hashCode method

### PR DESCRIPTION
**Pull request by tmoreira2020**

### CODE REVIEW

**Comment by tmoreira2020** [comment]
1. NPE won't happen because there is treatment for that, take a closer look into the if statements.
2. maxPrice and minPrice fields still exist, the change were made only in the methods.

**Comment by milczarekIT** [comment]
Sorry @tmoreira2020 - my fault, you are right.

Yes, maxPrice and minPrice fields still exist, but the question is why...

**Comment by tmoreira2020** [comment]
Yeah, it is really strange that the interface changed but the implementation didn't. For sure the developer missed that.

**Comment by team172011** [comment]
Thanks, @tmoreira2020! Yes, fields should be refactored, too.

**Pull request merged**
