### PR TITLE
Bar aggregator

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- add new methods for bar aggregation (upscaling): aggregateTimeSeries(), aggregateBars()
- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
Method allows to upscale a list of bars from lower timePeriod to higher timePeriod.

If you want, add more test cases or refine or optimise code.

**Comment by decebals** [comment]
Another idea is to move all these static helper methods in a separate utils class (`TimeSeriesUtils` for example). In this mode the size of `BaseTimeSeries` class decrease considerable.

**Comment by nimo23** [comment]
Yes, good idea. TimeSeriesUtils (or in future: BarSeriesUtils).

**Comment by milczarekIT** [comment]
I agree with @decebals. These changes should not be included in `BaseTimeSeries`. It can be done in `TimeSeriesUtils `, but in my opinion, there can be a separate component responsible for bars aggregation e.g. `BarAggregator` without static methods.

Please notice that a current method signature looks like:
`public static List<Bar> aggregateBars(List<Bar> bars, Duration timePeriod)`

It has `Bar` in the signature so it is not specific for a BaseBar. What is more, please remember that it is a library so it should be flexible. In this case, it makes sense to have BarAggregator interface with one (for this moment) implementation, It can be easily extended by user in its application.

**Comment by nimo23** [comment]
We can create a new package **"core/utils"** in which we can store such things: "core.utils.BarAggregator" with the provided static methods . Such things should not be within the root "core"..

@milczarekIT  I dont see any sense in providing an interface for BarAggregator. As you saw, the "Interface" is already build in by using the "Bar"-Interface within method signature. And I also dont see any sense in providing an object for BarAggregator..why one should create a constructor only to invoke a method?

**Comment by nimo23** [comment]
https://github.com/ta4j/ta4j/pull/420

**Pull request closed without merging**
