### PR TITLE
Introduced NumFactory and other factories

### LINKED ISSUE #1134: Suggestion for improving the organization of the proyect folders and classes
After reviewing the folder and class organization of this project, I have noticed that there is a large number of classes included solely in the core, without belonging to any specific folder, which often makes it difficult to efficiently locate classes while using the software.
As a suggestion, I propose implementing a cleaner organization by creating new folders for trade, position, strategy, etc. Additionally, including classes such as Indicator or Analysis Criterion in their respective folders. 

Implementing a model folder would also be a good proposal for this project, where all information related to the classes can be included.

### LINKED ISSUE #1144: Indicator and BarSerie should not be responsible for managing constants nor series
**Is your feature request related to a problem? Please describe.**
Interface changes made in https://github.com/ta4j/ta4j/pull/909/commits/1d36ab36e32f282048c0228a02c08e8a0006b4a7
in my opinion break single responsibility principle and cause performance issues, circa 5% slow down.

These methods are not related to BarSerie, but number type used in BarSerie, which should not leak to interface, because it is implementation detail.

```java
    /**
     * @return the related bar series
     */
    BarSeries getBarSeries();

    /**
     * @return the Num of 0
     */
    default Num zero() {
        return getBarSeries().zero();
    }

    /**
     * @return the Num of 1
     */
    default Num one() {
        return getBarSeries().one();
    }

    /**
     * @return the Num of 100
     */
    default Num hundred() {
        return getBarSeries().hundred();
    }

    /**
     * @return the {@link Num Num extending class} for the given {@link Number}
     */
    default Num numOf(Number number) {
        return getBarSeries().numOf(number);
    }
```

**Describe the solution you'd like**
Remove these methods form Indicator nad BarSerie interfaces and provide closer encapsulation for used datatype,
which may provide constants ZERO, HUNDRED, ONE etc. in specific data type and save about 5 % of runtime.

BarSerie and Indicator may provide method ```NumFactory numFactory()``` for parsing nonconstant values.

From my perspective this proposal also cleans internal implementation flow. From barSerie.giveMeNumber to barSerie.giveMeFactory.giveMeYourNumberWhichMayBeCached.

From User perspective it elimitatest question "Why BarSerie returns numbers?".

### PR DESCRIPTION
**Pull request by sgflt**
- cleaned tests
- use builders
- eliminated different parameter orders
- enforced usage of builder that belongs to series
- introduced possibility for caching most common constant values - one, two, hundred...

- TODO remove constructors in BaseBar and use BaseBarBuilder

Partially Fixes #1134.
Fixes #1144

Changes proposed in this pull request:
- standardize building flow
- remove ambiguous tons of methods and constructors with random parameter order
- f.e. Bar had open, hi, lo, close, Serie had open, close, hi, lo...
- 
- 

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by sgflt** [comment]
Most of tests passed. Last two I am going to fix later.

Implementing tests is now much easier, Mock* builders fill mandatory fields that are not tested. Implementor may focus only on values, that are related to tested Indicator/Rule/Criterion.

At first glance is visible, what properties of bar Indicator/Rule/Criterion uses.

**Comment by TheCookieLab** [comment]
Still in draft?

**Review by TheCookieLab — CHANGES_REQUESTED** [review]
The PR fails the automated checks due to missing license headers. Please run the formatter via `-B clean license:format formatter:format` as described in the contribution policy.

**Review by TheCookieLab — CHANGES_REQUESTED** [review]
See test errors in latest build:

```
Tests in error: 
  usingBarCount3UsingClosePriceMovingSerie[Test Case: 0 (0=DoubleNum, 1=DecimalNum)](org.ta4j.core.indicators.SMAIndicatorTest): Cannot add a bar with end time:1970-08-08T00:00Z[Etc/UTC] that is <= to series end time: 2024-07-06T16:21:02.895328Z[Etc/UTC]
  usingBarCount3UsingClosePriceMovingSerie[Test Case: 1 (0=DoubleNum, 1=DecimalNum)](org.ta4j.core.indicators.SMAIndicatorTest): Cannot add a bar with end time:1970-08-09T00:00Z[Etc/UTC] that is <= to series end time: 2024-07-06T16:21:02.935491Z[Etc/UTC] 
```

This is likely the same issue as https://github.com/ta4j/ta4j/issues/1165. Will need to alter bar building approach so that it doesn't implicitly rely on sequential execution.

**Comment by TheCookieLab** [comment]
Can you merge in the latest from master? Hopefully the conflict resolution is straightforward.

**Comment by sgflt** [comment]
I have just quickly fix compilation. There is still possible test clean up tha t might be done later. Mostly switching in new code to builders and removal of unrelevant data, fe. hi, lo, open for indicators that do not use them.

Time is generated automaticaly from mocked Clock instance so the real time should not be issue for fast computers, because it is simulated.

**Review by TheCookieLab — APPROVED** [review]

**Pull request merged**
