### PR TITLE
added code and unit test

### LINKED ISSUE #64: enhance "JustOnceRule"
**JustOnceRule** should assert that a rule is fired only one time and then never again. It should behave like the rule for "CrossedUp/CrossedDownRule" (which only fires one time as soon as the rule is satisfied and then never again).

However, I cannot put a rule within JustOnceRule, which I want to fire only one time. So for example, this is actually not possible:

```
// Fires only one time as soon as the actual value is higher than its two previous values.
// Even if the "next value" is also higher than its 2 previous values, 
// the rule is no more fired, because of JustOnceRule.
new JustOnceRule(isRisingRule(2));
```

Would be nice to enhance the "JustOnceRule" to made the above example possible.

### PR DESCRIPTION
**Pull request by TheCookieLab**
Fixes #64 

Changes proposed in this pull request:
- Add alternate constructor that takes in an "inner" rule

- [ ] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by team172011** [comment]
Cann you add an entry to the CHANGELOG.md and make a PR to `develop` branch, please?

**Comment by TheCookieLab** [comment]
Ah my mistake. I just now got my new ta4j core repo set up. I should've taken some time to read over the contribution rules.

**Comment by team172011** [comment]
No worries, i am pleased about every contribution!

**Comment by TheCookieLab** [comment]
How should I go about updating the CHANGELOG.md - do I create a new 0.11 section?

**Pull request closed without merging**
