### PR TITLE
BarSeriesUtils

### PR DESCRIPTION
**Pull request by nimo23**
Added TimeSeriesUtils with various helper methods:

- aggregateBars (easy aggregation of barSeries)
- replaceBarIfChanged (checks barSeries for new bars)
- findMissingBars (checks barSeries for missing bars)

- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
replaces https://github.com/ta4j/ta4j/pull/434

**Comment by nimo23** [comment]
Build failed because of :

`Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.10.0:validate (default-cli) on project ta4j-core: File '/home/travis/build/ta4j/ta4j/ta4j-core/src/main/java/org/ta4j/core/utils/TimeSeriesUtils.java' has not been previously formatted.  Please format file and commit before running validation! `

**Comment by team172011** [comment]
Can you run `mvn formatter:format` to Format your code and push again?

**Comment by nimo23** [comment]
> Can you run mvn formatter:format to format your code and push again?

I could, but I dont see any sense here. Because: this should not be the way for users to commit. If users use code formatter of IDE and are forced to use maven plugin, then this is not okay. 

Would be better to integrate this maven task within CI of this repo. With this, the maven task is running behind the scene within the Travis CI build. Please update the CI to run the maven task automatically after PR is pushed by the user.

**Comment by team172011** [comment]
merged in #456 with enhanced travis ci script

**Comment by nimo23** [comment]
@team172011 I cannot see the merged version within the actual develop-branch. There is no `utils`-package.

**Comment by team172011** [comment]
@nimo23 I am sorry for  unjustified closing this PR. Unfortunately I cannot reopen this PR because the repository that submitted this PR has been deleted

**Pull request closed without merging**
