### PR TITLE
Update DoubleNum.java: improve semantic of code

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- improve semantic of code due to https://github.com/ta4j/ta4j/pull/876

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
>avoiding nameshadowing is a thing to watch out for if impl classes start to create the same static symbols, private or otherwise.

This is not a reason for bad or cryptic naming. If someone wants to extend DoubleNum, then one can choose any name but the lib should be clear and use good naming schemes. Dirty code starts with dirty names..

**Comment by nimo23** [comment]
We take simple names (`ONE`) instead of complicating things (`D1_0`)..

So yes, something like the name `D1_0` is very cryptic:)

**Comment by nimo23** [comment]
>I'm going to say I disagree, given the potential code-completion headaches of so much self-importance

So you see, ONE is a pretty common and understandable name instead of `D1_0`.

It would be really nice not to waste our time on such trivial things. I don't have time for this kind of arguing.

**Comment by nimo23** [comment]
>forgive me for getting off-topic. 

No problem. It would be nice **not** to discuss such trivial things in the future, my and certainly your time is too precious for that.

Please answer the questions from https://github.com/ta4j/ta4j/pull/876. Currently, I'm inclined to remove the weak cache from your PR..

**Comment by nimo23** [comment]
>I am starting to see how this project gained a sudden drop in participation and activity.

So you think, that I am the reason? John., your _tireless_ kind is a bit overbearing. Stay polite! 

I just wanted to know whether the majority of the users benefit from the property `useCache` or if it's just you.  It would be nice if you included a test case in your https://github.com/ta4j/ta4j/pull/876 or at least a short example (with a benchmark?) how most of the users can benefit from `useCache`  nowadays. As I already said, @team172011 shouldn't have easily merged this PR without clearing any doubts from the community. So far I think it would be better to add the `useCache` in your own implementation (`MyDoubleNum`) instead of putting it into `DoubleNum`.

In addition, you have to realize for yourself that your PR falls far short of standard code quality requirements (Javadoc, property namings, changelog, etc.), hence this PR.

**Comment by johnthetireless** [comment]
> @johnthetireless are you seeing this? look familiar?

don't waste your time with this; you will argue and nothing will get done

**Comment by nimo23** [comment]
@jnorthrup == @johnthetireless you're talking to yourself..interesting :) Do you really think we're that dumb? Now don't act so innocent. Your initial posts (already deleted by you) of how YOU talked about me were very disrespectful. While I was constantly trying to contribute in an objective manner with improvements, questions, and suggestions, you were irrelevant and disrespectful to me. 

**Now finally and forever:** I won't talk to you anymore in the future. Take care and farewell!

**Comment by johnthetireless** [comment]
sorry jnorthrop.. i tried..  hehehe

**Pull request closed without merging**
