### PR TITLE
BaseBar:  cleanup constructors

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- removed all redundant constructors from BaseBar()
- adapt the used BaseBar constructors in some "src/test" and "ta4jexamples"
- added default constructors for double, BigDecimal, String
- added property "trades" in constructor

- [x] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
All **test cases** and **ta4jexamples** which make use of a **BaseBar()**-constructor could be replaced by BaseBarBuilder in the future.

**Comment by nimo23** [comment]
I added entries to changelog.

**Comment by nimo23** [comment]
I did notice the `Class<T> clazz` property of the following method  in `BaseBar.java` is not used within method. Am I right? If so, I can remove it this property from the arguments list..

public static <T> ConvertibleBaseBarBuilder<T> builder(
    Function<T, Num> conversionFunction, 
    Class<T> clazz) 
{
        return new ConvertibleBaseBarBuilder<>(conversionFunction);
}

**Comment by milczarekIT** [comment]
Hi 
`Class<T> clazz` is not used, but it is mandatory to deduce by compiler which type/function should be  used. 
You can try to remove it, but then code will not compile.

**Comment by milczarekIT** [comment]
> * added default constructors for double, BigDecimal, String
> * added property "trades" in constructor

In following discussion: https://github.com/ta4j/ta4j/issues/419 @team172011  and @decebals agreed that BarBuilder approach is better option. I agree with guys too.

Your PR duplicates features provided in https://github.com/ta4j/ta4j/pull/422, but you are using your approach with telescopic constructors.

What is more, you removed some constructor(s), so you introduced unncessary braking changes which are not compatible with version 0.12

**Comment by nimo23** [comment]
I added an entry to the changelog to notice users that unneccessary constructors are removed. This PR is finished and can be merged.

**Pull request merged**
