### PR TITLE
Refactoring: Trade renamed to Position, Order renamed to Trade

### PR DESCRIPTION
**Pull request by nimo23**
Fixes https://github.com/ta4j/ta4j/issues/466

Changes proposed in this pull request:
- **Breaking:** **Trade.class** renamed to **Position.class**
- **Breaking:** **Order.class** renamed to **Trade.class**

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
@team172011 I have carefully refactored all the code (with javadoc and comments) to reflect our new `Position.class` and `Trade.class`.

I did **not** abbreviate _Position_ to _Pos_, because it is far clearer. We should also not abbreviate it within the code as _pos_ is too common for variable names, we should always name it _position_.

While refactoring, I looked at the code and saw how much clearer it became with the new namings. No more irritations. Good work:)

**Comment by nimo23** [comment]
@team172011 Please merge this PR before all other outstanding PRs. I will re-create the other PR's as soon as this is merged. Thanks!

**Comment by nimo23** [comment]
@team172011 Please merge this PR before all other outstanding PRs. I will re-create the other PR's as soon as this is merged. Thanks!

**Comment by nimo23** [comment]
@team172011 Please merge this PR before all other outstanding PRs. I will re-create the other PR's as soon as this is merged. Thanks!

**Review by team172011 — APPROVED** [review]

**Comment by nimo23** [comment]
@team172011 Thanks for the quick response, I will correct the other pending PRs, so please dont merge it today.

**Pull request merged**
