### PR TITLE
[#973] Fix ParSarIndicator: recalculate all indices to always have correct context values

### LINKED ISSUE #973: [BUG] ParabolicSarIndicator throws NPE from getValue() method
`getValue()` method of `ParabolicSarIndicator` works, till bar series don't remove second bar from series. To reproduce bug I have wrote this small test:

```Java
    @Test
    public void growingBarSeriesTest() {
        List<Bar> bars = new ArrayList<>();
        bars.add(new MockBar(4120.98, 4086.29, 4211.08, 4032.62, numFunction));

        MockBarSeries mockBarSeries = new MockBarSeries(bars);
        mockBarSeries.setMaximumBarCount(4);

        mockBarSeries.addBar(new MockBar(4069.13, 4016.00, 4119.62, 3911.79, numFunction));
        mockBarSeries.addBar(new MockBar(4016.00, 4040.00, 4104.82, 3400.00, numFunction));
        mockBarSeries.addBar(new MockBar(4040.00, 4114.01, 4265.80, 4013.89, numFunction));
        mockBarSeries.addBar(new MockBar(4147.00, 4316.01, 4371.68, 4085.01, numFunction));
        mockBarSeries.addBar(new MockBar(4316.01, 4280.68, 4453.91, 4247.48, numFunction));

        ParabolicSarIndicator sar = new ParabolicSarIndicator(mockBarSeries);

        assertThrows(NullPointerException.class, () -> sar.getValue(mockBarSeries.getEndIndex()));
        assertThrows(NullPointerException.class, () -> sar.getValue(mockBarSeries.getEndIndex() - 1));
        assertThrows(NullPointerException.class, () -> sar.getValue(mockBarSeries.getEndIndex() - 2));
        assertThrows(NullPointerException.class, () -> sar.getValue(mockBarSeries.getEndIndex() - 3));
    }
```

### PR DESCRIPTION
**Pull request by team172011**
Fixes #973.

Changes proposed in this pull request:
- Fix ParSarIndicator: use time as key instead of index

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md` 
--> Fixes a fix in the next release (-  **Fixed** **ParabolicSarIndicator** fixed calculation for sporadic indices) no further entry needed

### CODE REVIEW

**Comment by team172011** [comment]
- [ ] I need to add assertion like "assertDoesNotThrows" to the new test provided by #973

**Review by TheCookieLab — APPROVED** [review]

**Comment by team172011** [comment]
Fix is not throwing any exception, but the results are still wrong because of the caching. It returns NaN for all indices

**Comment by TheCookieLab** [comment]
> Fix is not throwing any exception, but the results are still wrong because of the caching. It returns NaN for all indices

Ah I see. I can help take a look as well.

**Comment by TheCookieLab** [comment]
Oof upon running this myself it appears this bug is entwined with an underlying (and long-standing) issue with our caching layer. Might take a bit.

**Pull request merged**
