### PR TITLE
Fixed copyright notice from 2014-2017 to 2014-2018

### PR DESCRIPTION
**Pull request by MarijnKoesen**
Fixes #.

Changes proposed in this pull request:
- Fixed copyright notice from 2014-2017 to 2014-2018
- 
- 

- [ ] added an entry to the unreleased section of `CHANGES.md` 

Minor doc thingy.

### CODE REVIEW

**Comment by edlins** [comment]
@team172011 How does the license-maven-plugin work?

**Comment by team172011** [comment]
@edlins I think the `mvn licence` command should replace all header comments with the content in the LICENCE file. But actually the old licence comment will not be replaced, but the new will just be added to each file. This is because of much manually changes in licence so that the maven plugin does not detect it as comment anymore

**Comment by team172011** [comment]
I will update it with maven plugin

**Comment by edlins** [comment]
Cool.  How do you recommend contributors deal with license headers?  Don't touch, and do not add a license to new files?

**Comment by team172011** [comment]
I would say: Do not touch and add a exact copy of it to every new created java file. The eclipse Plug-In I use is very smart detecting changes, but other tools like our mvn plugin will not recognize it if some minor changes are done

**Pull request closed without merging**
