### PR TITLE
Feature for AndRule and OrRule to accept multiple rules

### PR DESCRIPTION
**Pull request by kduhyun**
### Summary
This feature is to accept multiple rules for AndRule and OrRule.
It will be useful to combine multiple rules like the following.

```
Rule entryRule = new OrRule(satisfiedRule, BooleanRule.TRUE, BooleanRule.TRUE);
Rule exitRule = new AndRule(satisfiedRule, BooleanRule.TRUE, BooleanRule.TRUE);
Rule complexRule = new OrRule(satisfiedRule.and(rule1, rule2, rule3), satisfiedRule2.and(rule1,rule2));
```

### Test
AndRuleTest
OrRuleTest

### CODE REVIEW

**Comment by team172011** [comment]
@kduhyun thanks for your contribution to this repository. I am unsure if this `little` enhancement justifies such a big change. I like the present approach that enables to link rules without the use of arrays and the need of iterating

**Comment by milczarekIT** [comment]
I agree with @team172011, old implementation is more cohesive

**Comment by yurivin** [comment]
I also like old implementation. May be there is a way to just add new method and constructor to old implementation.

**Comment by kduhyun** [comment]
Sorry. I was late.
Ok! As we agreed, I will close this PR. 

Thanks!

**Pull request closed without merging**
