### PR TITLE
Add: NumberOfConsecutivePositionsCriterion

### PR DESCRIPTION
**Pull request by nimo23**
Changes proposed in this pull request:
- :tada: **Enhancement** added **`NumberOfConsecutiveLosingPositionsCriterion`**

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
Currently, the internal logic of `NumberOfConsecutiveWinningPositionsCriterion` and `NumberOfConsecutiveLosingPositionsCriterion` is the same. Maybe we can merge both criterions into one: `NumberOfConsecutivePositionsCriterion` (and add constructor parameter to select if ConsecutiveWinnings or ConsecutiveLosings should be count).

**Comment by team172011** [comment]
> Currently, the internal logic of `NumberOfConsecutiveWinningPositionsCriterion` and `NumberOfConsecutiveLosingPositionsCriterion` is much the same. Maybe we can merge both criterions into one: `NumberOfConsecutivePositionsCriterion` (and add constructor parameter to select if ConsecutiveWinnings or ConsecutiveLosings should be count).

Maybe it is over engineered but my suggestion would be to combine both criteria into one `NumberOfConsecutivePositionsCriterion` that can be initialized with a `positionCompare` function

**Comment by nimo23** [comment]
@team172011 I added the `PositionFilter` in `AnalysisCriterions` which can be used for other criterions as well: This will lead to an overall simplification of the criterion package in general (by merging belonging criterions together (for example, replace `WinningPositionsRatioCriterion.java` and `LosingPositionsRatioCriterion.java` by `PositionsRatioCriterion.java` with the parameter PositionFilter. I will create another PR with such improvements.

This PR is finished.

**Comment by nimo23** [comment]
@team172011 please do not merge this PR, I will add a new PR for this after decisions of https://github.com/ta4j/ta4j/pull/759 are made.

**Comment by nimo23** [comment]
Replaced by https://github.com/ta4j/ta4j/pull/842

**Pull request closed without merging**
