### PR TITLE
add ContextTradingRecord with getCurrentTrade(int index)

### LINKED ISSUE #119: AnalysisCriterion start/finish indices
```
TradingRecord record = manager.run(strategy, startWindow, endWindow);
double improvement = new VersusBuyAndHoldCriterion(
     new TotalProfitCriterion()).calculate(series, record);
```
"improvement" will be the record (startWindow to endWindow) compared against buy-and-hold for the entire series.  This is not what I wanted so I added
```
public double calculate(TimeSeries series, TradingRecord tradingRecord,
     int startIndex, int finishIndex) {
        TradingRecord fakeRecord = new BaseTradingRecord();
        fakeRecord.enter(startIndex);
        fakeRecord.exit(finishIndex);
        return criterion.calculate(series, tradingRecord) / criterion.calculate(series, fakeRecord);
    }
```
and changed the code to
```
TradingRecord record = manager.run(strategy, startWindow, endWindow);
double improvement = new VersusBuyAndHoldCriterion(
     new TotalProfitCriterion()).calculate(series, record, startWindow, endWindow);
```
Not sure if this should belong here but if it's put in the AnalysisCriterion interface then all the implementing classes will need the addition.  Happy to submit a PR for this simpler change.

### PR DESCRIPTION
**Pull request by edlins**
Fixes #119 . (partial)

Changes proposed in this pull request:
- `getCurrentTrade(int index)` gives a context for defining the "current trade"
- Fix `TradingRecord.isClosed()`
- Rename TradingRecordTest to BaseTradingRecordTest

- [ ] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by edlins** [comment]
Maybe `getCurrentTrade(int index)` belongs in the `TradingRecord` interface?

**Comment by edlins** [comment]
`getCurrentTrade(int index)` belongs in the `TradingRecord` interface.  This is to support #119 .

Major simplification of the `ContextTradingRecord`.

I would be fine with this replacing `BaseTradingRecord` as it's a huge improvement.  There is a potential concern about performance of the linear search in `getCurrentTrade(int index)` but that can be further optimized if that's needed.

I also have concerns about `TradingRecord.enter()` and `TradingRecord.exit()` simply returning `false` when they fail.  I think they should probably throw exceptions.

**Comment by edlins** [comment]
Rebase, license updates, cleanup.

**Comment by edlins** [comment]
Still working on this.  The CPU penalty for the linear search is significant.

**Comment by edlins** [comment]
Performance is vastly improved using a `TreeMap` of `Trades` but is still slower than `BaseTradingRecord`.  May be able to do a little more cleanup.

**Comment by petoncle** [comment]
I'm not sure the word "context" is the right one to describe the concept. I have some difficulties understanding what it means. 

If I understand correctly, what we want is the ability to do some analysis on a sub-window of the time series, i.e. we want to do some analysis on a subset of contiguous bars instead of all the bars. So, why not simply create a new TimeSeries that contains the subset of bars you want, and do the analysis on that time series? Would that be possible?

A minor comment about the code: you currently have some unused imports, and you could make the code a bit more modern by using the diamond operator (e.g. replace new TreeMap<Integer, Trade>() by new TreeMap<>()).

**Comment by edlins** [comment]
> I'm not sure the word "context" is the right one to describe the concept.

It means, when `getCurrentTrade()` is called, it is passed an index parameter representing the time context.  Right now, `getCurrentTrade()` has zero parameters and thus only an implicit time context.  So it's like saying `what was the current trade at time index 10?` vs saying `what is the current trade?`.


> why not simply create a new TimeSeries that contains the subset of bars you want, and do the analysis on that time series?

Just seems unnecessary.  Waste of memory, and extra hoops to jump through but maybe similar CPU requirements.  But if this is the chosen method and it works I'll go with it.

It's been several months now but IIRC this PR originated from my attempts to run `VersusBuyAndHoldCriterion` on a subset of a `TimeSeries`.  It just doesn't work due to the implicit determination of `CurrentTrade` and/or the usage of `series.getBeginIndex()` / `series.getEndIndex()`.

I simply wanted to say `how did this strategy perform vs buy-and-hold from index 10 to index 100?` and was unable to do so in a straightforward manner.  Of course I'd have to dust this off to make sure IRC and provide a use case but it hasn't been a top priority.

**Pull request closed without merging**
