### PR TITLE
Restored PR: feature/numeric indicator core

### PR DESCRIPTION
**Pull request by team172011**
Changes proposed in this pull request:
- Added fluent design pattern with NumericIndicator
- Added facades for different indicators
- this is a copy of the deleted pr/817

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Review by team172011 — COMMENTED** [review]
Restored from pr #817

**Comment by johnthetireless** [comment]
you don't deserve to use this in your library... you don't deserve any contributors at all...
soon you will have none, I predict

please don't let people with basic programming skills, like nino23, mangle this too much
i don't use ta4j, so i really don't care, but it is the best thing in your lib - will be

shame on you people....

**Comment by team172011** [comment]
@johnthetireless I do not understand, what is your problem?

**Comment by nimo23** [comment]
@johnthetireless I also don't know why are you so offending - but I don't really care either. I really appreciate your contributions and yes, I don't say that I fully understand every single line of this lib at once - I am not perfect - it's a learning process for everyone. **Asking helps for learning - and I will not stop asking only because people like you don't like my questions.** No questions are stupid, only answers! But nevertheless, we are here together with one aim: to make this lib better, nothing more, nothing else. If you don't like me, it's ok. I really don't care - but please stop communication in such an offending and destructive way. I really like your contributions and I also hope that you will not stop in contributing because I think, that you have great experience and ideas, but I want you to stop to offend users or people using this lib or trying to make this lib better.

**Comment by johnthetireless** [comment]
If I were to try to contribute in the future - I will not, this will be the last you hear from me - here is what I would do.
I would follow the "how to contribute" page and submit a PR.  Then I would basically forget about it.
If there was some feedback I would make some changes, etc.
After 2-3 weeks of no feedback I would delete my local files and completely forget about it.
This is almost certainly what would happen, from what I have seen.  
I don't need the implied responsiblty that I will adjust things, add more tests, etc for an indefinite period.

The first PR I submitted to this project cleaned up some constuctor issues, 
so that only half as many array lists were created for the ADX indicators.
That was ready to be merged, I believe, but then a new release came out and I had merge conflicts.
I asked for help- - I sent you a message, but no reply.   Nimo told me to fix the conficting file myself.
I tried; git's bookkeeping was mixed up and I had no luck.  It may not have been possible from my end.
I am not good with git; I suspect someone else may have resolved it.
I closed that PR out of frustration, mostly.  It's probably still there; I don;t know about the branch.

Nothing came of that; nobody methioned it again.  This one you jumped and restored within a few hours.  
Personally, I think the ADX cleanup is more valuable. 
But this one is shiny and new.   This tells me a lot.  
 
Nimo talks about negative comments doing no good, but I find it hard to take very seriously.  I am reminded of the poor person who submitted a strange PR called "Analysis object" or something.  Was it really necessary to use 8-10 bullet points to send that person into therapy?  Judge me and look in the mirror.

Be well

**Comment by nimo23** [comment]
>That was ready to be merged, I believe, but then a new release came out and I had merge conflicts. I am not good with git; I suspect someone else may have resolved it.I asked for help- - I sent you a message, but no reply. 

I use Eclipse IDE with eGit (which is included by default) which simplifies most of the tasks..maybe you can have a look at it.

**Pull request merged**
