### PR TITLE
Introduce "EqualIndicatorRule"

### PR DESCRIPTION
**Pull request by nimo23**
Fixes #.

Changes proposed in this pull request:
- EqualIndicatorRule

- [ ] added an entry to the unreleased section of `CHANGES.md`

### CODE REVIEW

**Comment by nimo23** [comment]
If I have something like "AroonIndicator" and want to have a rule, which is satisfied, when value of Aroon is 100 (=highest high within the period), then I need this: 

return new EqualIndicatorRule(value, Decimal.valueOf(100));

**Comment by team172011** [comment]
Rule will be added, i missed it, too.

- Please make a pull request to the `developer ` branch. Pull requests to `master ` will not be merged.
- Rename rule to "IsEqualRule" to hold uniform naming

**Comment by team172011** [comment]
moved to a pull request into `develop `branch

**Comment by nimo23** [comment]
I did a PR with "IsEqualRule": https://github.com/ta4j/ta4j/pull/38.

**Pull request closed without merging**
