### PR TITLE
Fixed Ichimoku span A and span B calculations

### LINKED ISSUE #448: IchimokuChikouSpanIndicator calculation is wrong ?
IchimokuChikouSpanIndicator is today's price value plotted 26 period ago and not price 26 periods ago ? Has somebody used this indicator and please provide some explanation if possible.

Warm Regards,
Sudeep

### PR DESCRIPTION
**Pull request by jurepetrovic**
Fixes #448.

Changes proposed in this pull request:
Fixed Ichimoku span A and span B calculations.
Fixed unit tests.
Added calculation spreadsheet file
IchimokuLineIndicator not abstract anymore, because needs instantiation

### CODE REVIEW

**Comment by stoxalpha** [comment]
Hey @jurepetrovic  great work. Looked quickly at high level, but we would also need a easier way to get the current value of Span A and Span B which would be derived from 26 days and 52 days earlier values for today. That would be a very typical use case.

**Comment by jurepetrovic** [comment]
I don't understand what do you mean. 
You get today's values by invoking the indicator on today's index. 
If you want to get future values for spanA and spanB you invoke it with future index ;)

I'd like to get that in main branch if possible. 
Who is responsible for that? @team172011  ? 
Please advise.

**Comment by team172011** [comment]
thanks @jurepetrovic !

**Comment by stoxalpha** [comment]
This is still pending add to master branch :(

**Comment by stoxalpha** [comment]
Method threw 'java.lang.IndexOutOfBoundsException' exception.. Also we need to create a handle for this

**Comment by victorchung0325** [comment]
Just read the fix and found below line of code in IchimokuSenkouSpanAIndicator.java and IchimokuSenkouSpanBIndicator.java

int spanIndex = index - offset + 1;

I wonder why need to add one for the spanIndex? why not just minus the index by offset?

**Pull request merged**
